baseURL = "https://kakku.org/"
languageCode = "en"
title = "Amit Tripathi"
theme = "hyde-hyde"
author = "Amit Tripathi"

googleAnalytics = "UA-143063797-1"
disqusShortname = "kakku-org"
enableRobotsTXT = true
enableEmoji = true

summarylength = 30
paginate = 7

[params]
    author = "Amit Tripathi"
    authorimage = "/images/amittripathi.jpg"
    themeColor = "theme-base-01"
    layoutReverse = false
    relatedPosts = false
    dateformat = "Jan 2, 2006"
    postNavigation = true
    copyright = "Amit"
    showBuiltWith = true
    mainSections = ["posts"]
    highlightjs = true
    highlightjsstyle = "obsidian"

[permalinks]
    posts = "/:slug/"

[params.meta]
    description = "Amit Tripathi's blog :: technology, thoughts, opinions, travel"
    keywords = "blog,amitt001,python,software,engineer,golang,programming,travel"

[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 50
    url = "/"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about"

[params.social]
    github = "amitt001"
	twitter = "amitt019"
    linkedin = "amit-tripathi19"
	stackoverflow = "4440675"
    instagram = "iamit19"


# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank
    # between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related
    # pages.
    includeNewer = false
    # Will lower case keywords in both queries and in the indexes.
    toLower = false
[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
